/**
 * Fetches chick configuration data from the harnest GitHub repository
 * and generates a TypeScript data file for the website.
 *
 * Tries GitHub API first, falls back to local ../harnest directory.
 */

import https from 'node:https'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const OUTPUT = path.join(ROOT, 'src', 'data', 'chicks.generated.ts')
const LOCAL_NEST = path.join(ROOT, '..', 'harnest', 'nest')
const REPO = 'gioperalto/harnest'

// ── GitHub API helpers ──────────────────────────────────────────────────────

function githubFetch(apiPath) {
  const url = `https://api.github.com/repos/${REPO}/contents/${apiPath}`
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': 'harnest-website-build', Accept: 'application/vnd.github.v3+json' } }, (res) => {
        let data = ''
        res.on('data', (chunk) => (data += chunk))
        res.on('end', () => {
          if (res.statusCode !== 200) reject(new Error(`GitHub API ${res.statusCode}: ${data.slice(0, 200)}`))
          else resolve(JSON.parse(data))
        })
      })
      .on('error', reject)
  })
}

async function fetchFromGitHub() {
  console.log('Fetching chick data from GitHub API...')
  const entries = await githubFetch('nest')
  const dirs = entries.filter((e) => e.type === 'dir').map((e) => e.name)

  const chicks = []
  for (const dir of dirs) {
    try {
      const file = await githubFetch(`nest/${dir}/harnest.yaml`)
      const content = Buffer.from(file.content, 'base64').toString('utf-8')
      const parsed = yaml.load(content)
      chicks.push(extractChickData(dir, parsed))
      console.log(`  ✓ ${dir}`)
    } catch (err) {
      console.warn(`  ⊘ ${dir}: ${err.message}`)
    }
  }
  return chicks
}

// ── Local fallback ──────────────────────────────────────────────────────────

function fetchFromLocal() {
  console.log(`Falling back to local directory: ${LOCAL_NEST}`)
  if (!fs.existsSync(LOCAL_NEST)) {
    throw new Error(`Local harnest directory not found at ${LOCAL_NEST}`)
  }

  const dirs = fs
    .readdirSync(LOCAL_NEST, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)

  const chicks = []
  for (const dir of dirs) {
    const yamlPath = path.join(LOCAL_NEST, dir, 'harnest.yaml')
    if (!fs.existsSync(yamlPath)) continue
    const content = fs.readFileSync(yamlPath, 'utf-8')
    const parsed = yaml.load(content)
    chicks.push(extractChickData(dir, parsed))
    console.log(`  ✓ ${dir}`)
  }
  return chicks
}

// ── Data extraction ─────────────────────────────────────────────────────────

function extractChickData(dirName, parsed) {
  const agents = []
  if (parsed.agents) {
    for (const [key, value] of Object.entries(parsed.agents)) {
      agents.push({
        id: key,
        model: value.model || 'sonnet',
        count: value.count || 1,
        description: (value.description || '').trim(),
      })
    }
  }

  return {
    id: dirName,
    name: parsed.team?.name || dirName,
    description: (parsed.team?.description || '').trim(),
    agents,
  }
}

// ── Output generation ───────────────────────────────────────────────────────

function writeOutput(chicks) {
  // Sort alphabetically by id for stable output
  chicks.sort((a, b) => a.id.localeCompare(b.id))

  const ts = `// Auto-generated by scripts/fetch-chicks.mjs — do not edit manually

export interface ChickAgent {
  id: string
  model: string
  count: number
  description: string
}

export interface ChickData {
  id: string
  name: string
  description: string
  agents: ChickAgent[]
}

export const chicksData: ChickData[] = ${JSON.stringify(chicks, null, 2)}
`

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
  fs.writeFileSync(OUTPUT, ts, 'utf-8')
  console.log(`\nWrote ${chicks.length} chick(s) to ${path.relative(ROOT, OUTPUT)}`)
}

// ── Main ────────────────────────────────────────────────────────────────────

async function main() {
  let chicks
  try {
    chicks = await fetchFromGitHub()
  } catch (err) {
    console.warn(`GitHub API failed: ${err.message}`)
    chicks = fetchFromLocal()
  }

  if (chicks.length === 0) {
    console.error('No chick data found — aborting.')
    process.exit(1)
  }

  writeOutput(chicks)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
